### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by chaoyuxie** [chaoyuxie/video-stitching#1]
- [x] 1. 光心对齐的配准算法

- [x] 2.先用6个相机的gopro拍一段室外和一段室内视频（建议科技楼大厅）。内容有运动物体，跨相机接缝。

- [x] 3.跑实验：基于光心对齐的假设，拼全景视频。

- [x] 4. 分析光心对齐假设下的实验结果（主要看接缝对齐、结构变形，时序跳变）
